export class Meter {
  public ISUMLVL: number
  public TEMPCO: number
  public Run: number
  public IPEAK: number
  public VPEAK: number
  public STATUS0: number
  public STATUS1: number
  public OILVL: number
  public OVLVL: number
  public SAGLVL: number
  public MASK0: number
  public MASK1: number
  public CHECKSUM: number
  public VNOM: number
  public LAST_RWDATA32: number
  public PHSTATUS: number
  public ANGLE0: number
  public ANGLE1: number
  public ANGLE2: number
  public PHNOLOAD: number
  public LINECYC: number
  public ZXTOUT: number
  public CFMODE: number
  public CF1DEN: number
  public CF2DEN: number
  public CF3DEN: number
  public CONFIG: number
  public MMODE: number
  public ACCMODE: number
  public LCYCMODE: number
  public PEAKCYC: number
  public SAGCYC: number
  public CFCYC: number
  public HSDC_CFG: number
  public Version: number
  public CONFIG3: number
  public LAST_RWDATA8: number
  public APNOLOAD: number
  public VARNOLOAD: number
  public VANOLOAD: number
  public LAST_ADD: number
  public LAST_RWDATA16: number
  public LAST_OP: number
  public WTHR: number
  public VARTHR: number
  public VATHR: number
  public CONFIG2: number
}