export class Phase {
  public IGAIN: number
  public VGAIN: number
  public V2GAIN: number
  public IRMSOS: number
  public VRMSOS: number
  public V2RMSOS: number
  public PGAIN: number
  public WATTOS: number
  public VAROS: number
  public FWATTOS: number
  public FVAROS: number
  public FIRMSOS: number
  public FVRMSOS: number
  public TEMP0: number
  public TGAIN: number
  public IRMS: number
  public VRMS: number
  public V2RMS: number
  public TEMP: number
  public WATTHR: number
  public FWATTHR: number
  public VARHR: number
  public FVARHR: number
  public VAHR: number
  public WATT: number
  public VAR: number
  public VA: number
  public VTHD: number
  public ITHD: number
  public FIRMS: number
  public FVRMS: number
  public PHCAL: number
  public TEMPOS: number
  public PF: number
  public PERIOD: number
  public IWV: number
  public VWV: number
  public V2WV: number

}